### ISSUE TITLE
Pod install erro

### ISSUE THREAD

**Issue by ThanhQuang1410** [shaqian/react-native-ssh-sftp#19]
HI. I am using React Native 0.63.2 and trying to implement your library. When I reached to Pod install path I got this error. Can you have a look into it. Thanks

`
[!] The 'Pods-vhomes_v2' target has libraries with conflicting names: libssl.a and libcrypto.a.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error: 
[!] use_native_modules! skipped the react-native dependency 'react-native-ssh-sftp'. No podspec file was found.

    at CocoaPodsPackageManager._installAsync (/Users/creative/.npm/_npx/43767/lib/node_modules/pod-install/build/index.js:2:81979)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

**Comment by CodingByJerez** [comment]
Hello,
 I have the exact same error, did you find a solution?

**Comment by Bredansky** [comment]
Same error.

**Comment by miuel** [comment]
Hello, same error, when I did pod install

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error
    `at CocoaPodsPackageManager._installAsync (/Users/maikol/.npm/_npx/9068/lib/node_modules/pod-install/build/index.js:2:75999)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

before that I had to re-install cocoapods from brew... 

Anyone found a solution ? thanks.

**Comment by Bredansky** [comment]
Actually, it happens because of conflicting libraries OpenSSL (provided by React Native by default starting from 0.62 version to support Flipper, If I understand correctly) and NMSHH from react-native-ssh-sftp. They use dependent libraries with the same name. 

You can just create a React Native project with an older version. 0.61 as an option. 

Also, I have tried to rebuild NMSSH manually to get rid off the repeating libraries, but it was not successful. So, unfortunately, there is no way to run current react-native-ssh-sftp on the latest React Native project right now.

**Comment by Bredansky** [comment]
Okay, I found out you can build a project on a 0.63 version of RN commenting out the Flipper part in `Podfile`.

```
target 'rnssh' do
  pod 'NMSSH', '2.2.8'
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'rnsshTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'rnssh-tvOS' do
  # Pods for rnssh-tvOS

  target 'rnssh-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
```
