### ISSUE TITLE
App crash when trying to close shell

### ISSUE THREAD

**Issue by bodaghialib4** [shaqian/react-native-ssh-sftp#22]
hi,

I am using `react-native-ssh-sftp` as an ssh shell. It works fine. But when I try to close the ssh shell, my app crash.
I get the below logs from `adb logcat` command.

```
RNSSHClient: Error starting shell: Stream closed
AndroidRuntime: FATAL EXCEPTION: Thread-19
AndroidRuntime: Process: com.remotefilemanager, PID: 10904
AndroidRuntime: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
AndroidRuntime: 	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:25)
AndroidRuntime: 	at com.reactlibrary.RNSshClientModule$3.run(RNSshClientModule.java:200)
AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
ActivityTaskManager:   Force finishing activity com.remotefilemanager/.MainActivity
```

It seems that the callback of `startShell` invoked more than one time. first when the shell started correctly and then when I closed the shell and got the error in reading from the stream(BufferedReader).

Please help me to fix this problem.

my testing enviroment information:
- platform: android 10 (emulator)
- react: "16.9.0"
- react-native: "0.61.5"
- react-native-ssh-sftp: "^1.0.3",

**Comment by zejiazzz** [comment]
Hi, I also encountered this problem, please tell me if your problem is solved?

**Comment by FuwenChen** [comment]
I have the same problem, have you solved it and can you tell me the solution?

**Comment by bodaghialib4** [comment]
I could not find a good solution. But I found the cause of the error.

<img width="986" alt="Screen Shot 1400-09-20 at 22 39 40" src="https://user-images.githubusercontent.com/23075818/145688754-14de06f2-204a-4fc7-bd55-9206caf4a69a.png">



when we try to close the shell, in line 186 it gets an error and  `try/catch` trying to handle it. but it causes calling `callback.invoke()` two times. 

so for a temporary solution, after installing liberary, I remove `callback.invoke(error.getMessage());` in catch parts (lines 197&200 in `RNSshClientModule.java` of liberary).
but I need to repeat it after any yarn command.

dear @shaqian, 
could you please fix this?
